# Generated by CoffeeScript 1.12.7
Model = undefined
PI = undefined
TWO_PI = undefined
formaDoBaterDasAsas = undefined
mixerList = undefined

formaDoBaterDasAsas = (anguloDoCiclo, fBater, fRetorno, limiarShared) ->
    `var theta`
    theta = undefined
    d = undefined
    descida = undefined
    dh = undefined
    fD = undefined
    fS = undefined
    ferocidade = undefined
    limiar = undefined
    limiarFP = undefined
    ramp = undefined
    t = undefined
    theta = undefined
    if fBater >= 7.999 and fRetorno >= 7.999
        theta = anguloDoCiclo % TWO_PI
        if theta < 0
            theta += TWO_PI
        limiarFP = if limiarShared != null then limiarShared else PI
        if theta < limiarFP
            return 1.0
        else
            return -1.0
    theta = anguloDoCiclo % TWO_PI
    if theta < 0
        theta += TWO_PI
    fD = Math.max(0, Math.min(8, fBater))
    fS = Math.max(0, Math.min(8, fRetorno))
    limiar = if limiarShared != null then limiarShared else TWO_PI * 0.5
    descida = theta < limiar
    t = if descida then theta / limiar else (theta - limiar) / (TWO_PI - limiar)
    ferocidade = if descida then fD else fS
    d = ferocidade / 8.0
    dh = d * 0.5
    if d >= 1.0
        if descida
            return 1.0
        else
            return -1.0
    if t < dh
        if descida
            return 1.0
        else
            return -1.0
    if t > 1.0 - dh
        if descida
            return -1.0
        else
            return 1.0
    ramp = Math.cos(PI * (t - dh) / (1.0 - d))
    if descida
        ramp
    else
        -ramp

'use strict'
mixerList = []
mixerList[27] =
    name: 'Ornithopter'
    model: 'custom'
    image: 'ornithopter'
TWO_PI = 2 * Math.PI
PI = Math.PI

Model = (wrapper, canvas, waveCanvas) ->
    ambient = undefined
    directional = undefined
    mixer = undefined
    model_file = undefined
    onMouseDown = undefined
    onMouseMove = undefined
    onMouseUp = undefined
    onWheel = undefined
    pairCount = undefined
    useWebGLRenderer = undefined
    useWebGLRenderer = @canUseWebGLRenderer()
    @wrapper = wrapper
    @canvas = canvas
    @waveCanvas = if waveCanvas and waveCanvas.length then waveCanvas[0] else waveCanvas or null
    @lockView = false
    @waveCtx = if @waveCanvas then @waveCanvas.getContext('2d') else null
    @animationFrame = null
    @lastFlapTime = 0
    @flapAngle = 0
    @waveHistory = []
    @WAVE_LEN = 200
    @servoData = null
    @servoTimestamp = 0
    @SERVO_TIMEOUT = 150
    @flapParams =
        throttle: 1280
        yaw: 1500
        frequency: 6.0
        amplitude: 30.0
        aeroelasticCoef: 0.0
        glideAeroCoef: 0.0
        glideAnglesL: null
        glideAnglesR: null
        ferocityDown: 4.0
        ferocityUp: 4.0
        ferocityDownL: [
            4.0
            4.0
            4.0
            4.0
        ]
        ferocityDownR: [
            4.0
            4.0
            4.0
            4.0
        ]
        ferocityUpL: [
            4.0
            4.0
            4.0
            4.0
        ]
        ferocityUpR: [
            4.0
            4.0
            4.0
            4.0
        ]
        phaseShifts: [
            0
            0
            0
            0
        ]
        mountAngles: [0, 0]
        mountAnglesL: [20, -20]
        mountAnglesR: [-20, 20]
        servoCount: 4
    @servoAngles = []
    @_prevFlapZL = []
    @_prevFlapZR = []
    if useWebGLRenderer
        @renderer = new (THREE.WebGLRenderer)(
            canvas: @canvas[0]
            alpha: true
            antialias: true)
    else
        @renderer = new (THREE.CanvasRenderer)(
            canvas: @canvas[0]
            alpha: true)
    @renderer.setSize @wrapper.width() * 2, @wrapper.height() * 2
    @scene = new (THREE.Scene)
    @modelWrapper = new (THREE.Object3D)
    @modelWrapper.rotation.order = 'YXZ'
    @camera = new (THREE.PerspectiveCamera)(60, @wrapper.width() / @wrapper.height(), 1, 10000)
    @camera.position.set 0, 30, 125
    @camera.lookAt new (THREE.Vector3)(0, 0, 0)
    @_orbit =
        dragging: false
        theta: 0
        phi: 0.24
        radius: 128
        prevX: 0
        prevY: 0
    onMouseDown = ((_this) ->
        (e) ->
            if e.button != 0 then return
            _this._orbit.dragging = true
            _this._orbit.prevX = e.clientX
            _this._orbit.prevY = e.clientY
            e.preventDefault()
    )(this)
    onMouseMove = ((_this) ->
        (e) ->
            dx = undefined
            dy = undefined
            if !_this._orbit.dragging
                return
            dx = e.clientX - (_this._orbit.prevX)
            dy = e.clientY - (_this._orbit.prevY)
            _this._orbit.theta -= dx * 0.01
            _this._orbit.phi = Math.max(-PI * 0.45, Math.min(PI * 0.45, _this._orbit.phi + dy * 0.01))
            _this._orbit.prevX = e.clientX
            _this._orbit.prevY = e.clientY
            _this._updateCameraOrbit()
    )(this)
    onMouseUp = ((_this) ->
        (e) ->
            _this._orbit.dragging = false
    )(this)
    onWheel = ((_this) ->
        (e) ->
            _this._orbit.radius = Math.max(40, Math.min(500, _this._orbit.radius + e.deltaY * 0.3))
            _this._updateCameraOrbit()
            e.preventDefault()
    )(this)
    @_updateCameraOrbit = ((_this) ->
        ->
            _this.camera.position.x = _this._orbit.radius * Math.sin(_this._orbit.theta) * Math.cos(_this._orbit.phi)
            _this.camera.position.y = _this._orbit.radius * Math.sin(_this._orbit.phi)
            _this.camera.position.z = _this._orbit.radius * Math.cos(_this._orbit.theta) * Math.cos(_this._orbit.phi)
            _this.camera.lookAt new (THREE.Vector3)(0, 0, 0)
    )(this)
    @canvas.on 'mousedown', onMouseDown
    $(document).on 'mousemove', onMouseMove
    $(document).on 'mouseup', onMouseUp
    @wrapper.on 'wheel', onWheel
    ambient = new (THREE.AmbientLight)(0x404040)
    directional = new (THREE.DirectionalLight)(new (THREE.Color)(1, 1, 1), 1.5)
    directional.position.set 0, 1, 0
    @scene.add ambient
    @scene.add directional
    @scene.add @camera
    @scene.add @modelWrapper
    @_matFuselage = new (THREE.MeshPhongMaterial)(
        color: 0x2a3040
        specular: 0x111111
        shininess: 10)
    @_matWing = new (THREE.MeshPhongMaterial)(
        color: 0xf0c060
        specular: 0x111111
        shininess: 5
        transparent: true
        opacity: 0.75
        side: THREE.DoubleSide)
    @_matPivot = new (THREE.MeshPhongMaterial)(
        color: 0x5865f2
        specular: 0x111111
        shininess: 20)
    @_matHead = new (THREE.MeshPhongMaterial)(
        color: 0x3a4a5a
        specular: 0x111111
        shininess: 10)
    @_matTail = new (THREE.MeshPhongMaterial)(
        color: 0x2a3040
        specular: 0x111111
        shininess: 5
        side: THREE.DoubleSide)
    # Front-first ordering: index 0 = frontmost pair (nose = +Z). Normalized
    # station σ = z / 27.5 (half fuselage length) — matches simulator's
    # mount_distance convention (σ = +1 nose, −1 tail).
    @_pairZPositions =
        1: [ 0 ]
        2: [
            11
            -11
        ]
        3: [
            16
            0
            -16
        ]
        4: [
            18
            6
            -6
            -18
        ]
    mixer = if typeof MIXER_CONFIG != 'undefined' and MIXER_CONFIG.mixer then MIXER_CONFIG.mixer else 27
    pairCount = 2
    if typeof SERVO_CONFIG != 'undefined' and SERVO_CONFIG.length
        pairCount = Math.max(1, Math.min(4, Math.floor(SERVO_CONFIG.length / 2)))
    if mixer == 27
        @buildOrnithopter pairCount
        @startAnimation()
    else
        model_file = if useWebGLRenderer then (mixerList[mixer] or model: 'custom').model else 'fallback'
        if model_file == 'custom'
            model_file = 'fallback'
        @loadJSON model_file, ((model) ->
            @model = model
            @modelWrapper.add model
            @scene.add @modelWrapper
            @render()
            return
        ).bind(this)
    return

Model::loadJSON = (model_file, callback) ->
    loader = undefined
    loader = new (THREE.JSONLoader)
    loader.load './resources/models/' + model_file + '.json', (geometry, materials) ->
        model = undefined
        modelMaterial = undefined
        modelMaterial = new (THREE.MeshFaceMaterial)(materials)
        model = new (THREE.Mesh)(geometry, modelMaterial)
        model.scale.set 15, 15, 15
        callback model
        return
    return

Model::_buildFixedBody = ->
    fin = undefined
    finGeo = undefined
    fuselage = undefined
    fuselageGeo = undefined
    head = undefined
    headGeo = undefined
    tail = undefined
    tailGeo = undefined
    fuselageGeo = new (THREE.BoxGeometry)(8, 10, 55)
    fuselage = new (THREE.Mesh)(fuselageGeo, @_matFuselage)
    fuselage.position.set 0, 0, 0
    fuselage.name = 'fuselage'
    @modelWrapper.add fuselage
    headGeo = new (THREE.CylinderGeometry)(0, 4.5, 12, 8)
    head = new (THREE.Mesh)(headGeo, @_matHead)
    head.position.set 0, 2, 33
    head.rotation.x = PI / 2
    head.name = 'head'
    @modelWrapper.add head
    # Two triangular tail feathers in anhedral (bird-tail V-shape)
    makeTailFeather = (isLeft) ->
        sx = if isLeft then -1 else 1
        geo = new (THREE.Geometry)
        geo.vertices.push new (THREE.Vector3)( 0,    0,    0  )  # root at body
        geo.vertices.push new (THREE.Vector3)( sx*6, -3,  -14 )  # outer tip
        geo.vertices.push new (THREE.Vector3)( sx*2,  1.5, -5  )  # inner ridge
        geo.faces.push new (THREE.Face3)(0, 1, 2)
        geo.computeVertexNormals()
        return new (THREE.Mesh)(geo, @_matTail)
    leftFeather = makeTailFeather(true)
    leftFeather.position.set 0, 1, -24
    leftFeather.name = 'leftTailFeather'
    @modelWrapper.add leftFeather
    rightFeather = makeTailFeather(false)
    rightFeather.position.set 0, 1, -24
    rightFeather.name = 'rightTailFeather'
    @modelWrapper.add rightFeather
    return

Model::buildOrnithopter = (pairCount) ->
    leftPivot = undefined
    leftWing = undefined
    old = undefined
    p = undefined
    pp = undefined
    rightPivot = undefined
    rightWing = undefined
    s = undefined
    sphereGeo = undefined
    sphereL = undefined
    sphereR = undefined
    wingGeo = undefined
    wingPair = undefined
    z = undefined
    zPositions = undefined
    pairCount = Math.max(1, Math.min(4, pairCount or 2))
    if @wingPivots
        pp = 0
        while pp < @wingPivots.length
            old = @wingPivots[pp]
            if old.leftPivot
                @modelWrapper.remove old.leftPivot
            if old.rightPivot
                @modelWrapper.remove old.rightPivot
            pp++
    while @modelWrapper.children.length > 0
        @modelWrapper.remove @modelWrapper.children[0]
    @_buildFixedBody()
    @wingPivots = []
    wingGeo = new (THREE.BoxGeometry)(65, 0.8, 12)
    # Chord offset: leading edge at pivot, chord extends backward (-Z)
    CHORD_HALF = -6
    zPositions = @_pairZPositions[pairCount] or @_pairZPositions[2]
    p = 0
    while p < pairCount
        z = zPositions[p]
        wingPair =
            leftMount: null
            leftFlap: null
            leftAero: null
            rightMount: null
            rightFlap: null
            rightAero: null
        # Left wing hierarchy: Mount(Y=sweep) → Flap(Z=flapping) → Aero(Y=flex) → mesh(LE at pivot)
        leftMount = new (THREE.Object3D)
        leftMount.position.set -4.5, 1, z
        leftMount.name = 'wingPair' + p + '_leftMount'
        @modelWrapper.add leftMount
        leftFlap = new (THREE.Object3D)
        leftFlap.name = 'wingPair' + p + '_leftFlap'
        leftMount.add leftFlap
        leftAero = new (THREE.Object3D)
        leftAero.name = 'wingPair' + p + '_leftAero'
        leftFlap.add leftAero
        leftWing = new (THREE.Mesh)(wingGeo, @_matWing)
        leftWing.position.set -32.5, 0, CHORD_HALF
        leftAero.add leftWing
        wingPair.leftMount = leftMount
        wingPair.leftFlap = leftFlap
        wingPair.leftAero = leftAero
        # Right wing hierarchy: Mount(Y=sweep) → Flap(Z=flapping) → Aero(Y=flex) → mesh(LE at pivot)
        rightMount = new (THREE.Object3D)
        rightMount.position.set 4.5, 1, z
        rightMount.name = 'wingPair' + p + '_rightMount'
        @modelWrapper.add rightMount
        rightFlap = new (THREE.Object3D)
        rightFlap.name = 'wingPair' + p + '_rightFlap'
        rightMount.add rightFlap
        rightAero = new (THREE.Object3D)
        rightAero.name = 'wingPair' + p + '_rightAero'
        rightFlap.add rightAero
        rightWing = new (THREE.Mesh)(wingGeo, @_matWing)
        rightWing.position.set 32.5, 0, CHORD_HALF
        rightAero.add rightWing
        wingPair.rightMount = rightMount
        wingPair.rightFlap = rightFlap
        wingPair.rightAero = rightAero
        # Pivot indicator spheres at mount positions
        sphereGeo = new (THREE.SphereGeometry)(2, 8, 8)
        sphereL = new (THREE.Mesh)(sphereGeo, @_matPivot)
        sphereL.position.copy leftMount.position
        @modelWrapper.add sphereL
        sphereR = new (THREE.Mesh)(sphereGeo, @_matPivot)
        sphereR.position.copy rightMount.position
        @modelWrapper.add sphereR
        @wingPivots.push wingPair
        p++
    @flapParams.servoCount = pairCount * 2
    @servoAngles = []
    @_prevFlapZL = []
    @_prevFlapZR = []
    s = 0
    while s < pairCount * 2
        @servoAngles.push 0
        s++
    @render()
    return

Model::setPairCount = (n) ->
    @buildOrnithopter Math.max(1, Math.min(4, n or 2))
    return

Model::setServoPositions = (pwmArray) ->
    if !pwmArray or !pwmArray.length
        return
    @servoData = pwmArray.slice(0, 8)
    @servoTimestamp = performance.now()
    return

Model::startAnimation = ->
    _animLoop = undefined
    self = undefined
    self = this

    _animLoop = (timestamp) ->
        `var mountAngle`
        `var p`
        p = undefined
        mountAngle = undefined
        MAX_ANGLE_DEG = undefined
        PWM_NEUTRAL = undefined
        PWM_RANGE = undefined
        ampDeg = undefined
        amplitude = undefined
        angleL = undefined
        angleR = undefined
        dt = undefined
        fDL = undefined
        fDR = undefined
        fDarrL = undefined
        fDarrR = undefined
        fUL = undefined
        fUR = undefined
        fUarrL = undefined
        fUarrR = undefined
        freq = undefined
        leftAmp = undefined
        leftAngle = undefined
        mountAngle = undefined
        mountAngleL = undefined
        mountAngleR = undefined
        p = undefined
        pairCount = undefined
        phase = undefined
        phaseShift = undefined
        pwmL = undefined
        pwmL_clamped = undefined
        pwmR = undefined
        pwmR_clamped = undefined
        ref = undefined
        ref1 = undefined
        rightAmp = undefined
        rightAngle = undefined
        servoCount = undefined
        si = undefined
        siL = undefined
        siR = undefined
        throttle = undefined
        throttleFactor = undefined
        useServoData = undefined
        waveValL = undefined
        waveValR = undefined
        yaw = undefined
        yawDiff = undefined
        self.animationFrame = requestAnimationFrame(_animLoop)
        if !self.flapParams
            return
        dt = if self.lastFlapTime then (timestamp - (self.lastFlapTime)) * 0.001 else 0.016
        if dt <= 0
            dt = 0.001
        if dt > 0.1
            dt = 0.1
        self.lastFlapTime = timestamp
        freq = self.flapParams.frequency or 6.0
        self.flapAngle += freq * TWO_PI * dt
        if self.flapAngle > TWO_PI * 10
            self.flapAngle %= TWO_PI
        pairCount = if self.wingPivots then self.wingPivots.length else 0
        servoCount = pairCount * 2
        useServoData = self.servoData and self.servoTimestamp and performance.now() - (self.servoTimestamp) < self.SERVO_TIMEOUT
        if useServoData
            PWM_NEUTRAL = 1500
            PWM_RANGE = 500
            MAX_ANGLE_DEG = 45
            p = 0
            while p < pairCount
                siL = p * 2
                siR = p * 2 + 1
                pwmL = if siL < self.servoData.length then self.servoData[siL] else PWM_NEUTRAL
                pwmL_clamped = Math.max(1000, Math.min(2000, pwmL or PWM_NEUTRAL))
                angleL = (pwmL_clamped - PWM_NEUTRAL) / PWM_RANGE * MAX_ANGLE_DEG
                pwmR = if siR < self.servoData.length then self.servoData[siR] else PWM_NEUTRAL
                pwmR_clamped = Math.max(1000, Math.min(2000, pwmR or PWM_NEUTRAL))
                angleR = (pwmR_clamped - PWM_NEUTRAL) / PWM_RANGE * MAX_ANGLE_DEG
                mountAngle = self.flapParams.mountAngles[p] or 0
                self.wingPivots[p].leftMount.rotation.y = mountAngle * PI / 180
                self.wingPivots[p].rightMount.rotation.y = mountAngle * PI / 180
                self.wingPivots[p].leftFlap.rotation.z = angleL * PI / 180
                self.wingPivots[p].rightFlap.rotation.z = -angleR * PI / 180
                # Aeroelastic flex: downstroke→TE up, upstroke→TE down (both wings same)
                aeroCoef = self.flapParams.aeroelasticCoef or 0
                aeroFlex = aeroCoef * Math.cos(self.flapAngle) * PI / 180
                if self.wingPivots[p].leftAero
                    self.wingPivots[p].leftAero.rotation.x = aeroFlex
                if self.wingPivots[p].rightAero
                    self.wingPivots[p].rightAero.rotation.x = aeroFlex
                self.servoAngles[siL] = mountAngle + angleL
                self.servoAngles[siR] = mountAngle + angleR
                p++
        else
            throttle = self.flapParams.throttle or 1280
            yaw = self.flapParams.yaw or 1500
            amplitude = self.flapParams.amplitude or 30.0
            fDarrL = self.flapParams.ferocityDownL or [
                4.0
                4.0
                4.0
                4.0
            ]
            fDarrR = self.flapParams.ferocityDownR or [
                4.0
                4.0
                4.0
                4.0
            ]
            fUarrL = self.flapParams.ferocityUpL or [
                4.0
                4.0
                4.0
                4.0
            ]
            fUarrR = self.flapParams.ferocityUpR or [
                4.0
                4.0
                4.0
                4.0
            ]
            throttleFactor = Math.max(0, Math.min(1, (throttle - 1040) / 960))
            ampDeg = amplitude * throttleFactor
            yawDiff = (yaw - 1500) / 500
            leftAmp = Math.max(0, Math.min(55, ampDeg * (1.0 - (yawDiff * 0.7))))
            rightAmp = Math.max(0, Math.min(55, ampDeg * (1.0 + yawDiff * 0.7)))
            # Fore/aft amplitude differential — front vs rear pair for pitch control
            faDiff = self.flapParams.amplitudeFA or 0
            faDiff = Math.max(-0.8, Math.min(0.8, faDiff))
            # Accumulate ferocity for waveform reference (PID→ferocity→waveform shape)
            fdSum = 0.0; fuSum = 0.0
            p = 0
            while p < pairCount
                phaseShift = (self.flapParams.phaseShifts[p] or 0) * PI / 180
                mountAngleL = ((if (ref = self.flapParams.mountAnglesL) != null then ref[p] else undefined) or self.flapParams.mountAngles[p] or 0)
                mountAngleR = ((if (ref1 = self.flapParams.mountAnglesR) != null then ref1[p] else undefined) or self.flapParams.mountAngles[p] or 0)
                phase = self.flapAngle + phaseShift
                fDL = fDarrL[p] or 4.0
                fDR = fDarrR[p] or 4.0
                fUL = fUarrL[p] or 4.0
                fUR = fUarrR[p] or 4.0
                waveValL = formaDoBaterDasAsas(phase, fDL, fUL, null)
                waveValR = formaDoBaterDasAsas(phase, fDR, fUR, null)
                fdSum += fDL + fDR; fuSum += fUL + fUR
                # Per-pair amplitude: front +faDiff, rear −faDiff → pitch moment
                pairAmpMod = if p == 0 then 1.0 + faDiff else 1.0 - faDiff
                pLeftAmp  = leftAmp  * pairAmpMod
                pRightAmp = rightAmp * pairAmpMod
                self.wingPivots[p].leftMount.rotation.y = mountAngleL * PI / 180
                self.wingPivots[p].rightMount.rotation.y = mountAngleR * PI / 180
                # Flap centre offset: PID wing deflection. Same in glide (amp=0) & flapping.
                # Oscillation is ADDED on top — superposition: wing = centre + wave×amplitude.
                centreL = (self.flapParams.flapCenterL?[p] or 0) * PI / 180
                centreR = (self.flapParams.flapCenterR?[p] or 0) * PI / 180
                # Flap Z in radians — compute before applying to pivot
                flapZL = centreL + waveValL * pLeftAmp * PI / 180
                flapZR = -(centreR + waveValR * pRightAmp * PI / 180)
                self.wingPivots[p].leftFlap.rotation.z = flapZL
                self.wingPivots[p].rightFlap.rotation.z = flapZR
                # Aeroelastic flex: velocity-based — flex opposes wing motion (inertial lag).
                # Works identically in flapping (fast velocity→strong flex) and glide
                # (stick/PID-driven velocity→proportional flex). Zero when wings still.
                aeroCoef = self.flapParams.aeroelasticCoef or 0
                if dt > 0.0001 and aeroCoef > 0
                    self._prevFlapZL ?= []
                    self._prevFlapZR ?= []
                    velL = (flapZL - (self._prevFlapZL[p] or 0)) / dt
                    velR = (flapZR - (self._prevFlapZR[p] or 0)) / dt
                    # Scale: aeroCoef 0..40 → flex ~0..14° at 3 rad/s (normal flapping velocity)
                    aeroFlexL = -aeroCoef * velL * 0.0015
                    aeroFlexR = -aeroCoef * velR * 0.0015
                else
                    aeroFlexL = 0; aeroFlexR = 0
                self._prevFlapZL ?= []
                self._prevFlapZR ?= []
                self._prevFlapZL[p] = flapZL
                self._prevFlapZR[p] = flapZR
                if self.wingPivots[p].leftAero
                    self.wingPivots[p].leftAero.rotation.x = aeroFlexL
                if self.wingPivots[p].rightAero
                    self.wingPivots[p].rightAero.rotation.x = aeroFlexR
                si = p * 2
                self.servoAngles[si] = mountAngleL + (self.flapParams.flapCenterL?[p] or 0) + waveValL * pLeftAmp
                self.servoAngles[si + 1] = mountAngleR + (self.flapParams.flapCenterR?[p] or 0) + waveValR * pRightAmp
                p++
        # Store average ferocity for waveform plotter reference line
        nPairs = pairCount or 2
        self._avgFerocityDown = fdSum / (nPairs * 2)
        self._avgFerocityUp   = fuSum / (nPairs * 2)
        # Glide mode: when amplitude near zero and glideAeroCoef active,
        # set static wing Z-angles from PID corrections
        if ampDeg < 0.1 and self.flapParams.glideAeroCoef > 0 and self.flapParams.glideAnglesL and self.flapParams.glideAnglesR
            p = 0
            while p < pairCount
                gL = (self.flapParams.glideAnglesL[p] or 0) * PI / 180
                gR = (self.flapParams.glideAnglesR[p] or 0) * PI / 180
                self.wingPivots[p].leftFlap.rotation.z = gL
                self.wingPivots[p].rightFlap.rotation.z = -gR
                # Aeroelastic still active in glide (passive wing twist under load)
                aeroCoef = self.flapParams.aeroelasticCoef or 0
                aeroFlex = aeroCoef * Math.cos(self.flapAngle) * PI / 180
                if self.wingPivots[p].leftAero
                    self.wingPivots[p].leftAero.rotation.x = aeroFlex
                if self.wingPivots[p].rightAero
                    self.wingPivots[p].rightAero.rotation.x = aeroFlex
                si = p * 2
                mountL = self.wingPivots[p].leftMount.rotation.y * 180 / PI
                mountR = self.wingPivots[p].rightMount.rotation.y * 180 / PI
                self.servoAngles[si] = mountL + gL * 180 / PI
                self.servoAngles[si + 1] = mountR + gR * 180 / PI
                p++
        self.render()
        self.drawWavePlotter()
        return

    @animationFrame = requestAnimationFrame(_animLoop)
    return

Model::drawWavePlotter = ->
    `var j`
    `var s`
    `var xx`
    `var yy`
    s = undefined
    j = undefined
    xx = undefined
    yy = undefined
    AMP_REF = undefined
    H = undefined
    W = undefined
    ampY = undefined
    color = undefined
    cosVal = undefined
    ctx = undefined
    entry = undefined
    i = undefined
    isLeft = undefined
    j = undefined
    key = undefined
    labelY = undefined
    lastVal = undefined
    margin = undefined
    midY = undefined
    n = undefined
    pairIdx = undefined
    pairLabels = undefined
    ph = undefined
    pw = undefined
    s = undefined
    servoColors = undefined
    servoCount = undefined
    useServo = undefined
    val = undefined
    xScale = undefined
    xx = undefined
    y = undefined
    yy = undefined
    if !@waveCtx or !@waveCanvas
        return
    servoCount = if @servoAngles then @servoAngles.length else 4
    cosVal = Math.cos(@flapAngle)
    # Ferocity-shaped waveform — reacts to PID via _avgFerocityDown/Up set in _animLoop
    waveVal = if @_avgFerocityDown? and @_avgFerocityUp?
        formaDoBaterDasAsas(@flapAngle, @_avgFerocityDown, @_avgFerocityUp, null)
    else
        cosVal
    useServo = @servoData and @servoTimestamp and performance.now() - (@servoTimestamp) < @SERVO_TIMEOUT
    entry =
        sin: cosVal
        wave: waveVal
        live: useServo
    s = 0
    while s < servoCount
        entry['s' + s] = @servoAngles[s] or 0
        s++
    @waveHistory.push entry
    if @waveHistory.length > @WAVE_LEN
        @waveHistory.shift()
    ctx = @waveCtx
    W = @waveCanvas.width
    H = @waveCanvas.height
    ctx.clearRect 0, 0, W, H
    margin =
        top: 8
        right: 10
        bottom: 14
        left: 10
    pw = W - (margin.left) - (margin.right)
    ph = H - (margin.top) - (margin.bottom)
    midY = margin.top + ph / 2
    AMP_REF = 55
    ampY = ph / 2
    ctx.strokeStyle = 'rgba(48,54,61,0.6)'
    ctx.lineWidth = 0.5
    i = 0
    while i <= 4
        y = margin.top + ph * i / 4
        ctx.beginPath()
        ctx.moveTo margin.left, y
        ctx.lineTo W - (margin.right), y
        ctx.stroke()
        i++
    ctx.strokeStyle = '#30363d'
    ctx.lineWidth = 1
    ctx.beginPath()
    ctx.moveTo margin.left, midY
    ctx.lineTo W - (margin.right), midY
    ctx.stroke()
    n = @waveHistory.length
    if n < 2
        return
    xScale = pw / (n - 1)
    ctx.strokeStyle = '#58a6ff'
    ctx.lineWidth = 1.2
    ctx.globalAlpha = 0.3
    ctx.beginPath()
    j = 0
    while j < n
        xx = margin.left + j * xScale
        refVal = @waveHistory[j].wave or @waveHistory[j].sin or 0
        yy = midY - (refVal * ampY)
        if j == 0
            ctx.moveTo xx, yy
        else
            ctx.lineTo xx, yy
        j++
    ctx.stroke()
    ctx.globalAlpha = 1
    ctx.fillStyle = if useServo then '#3fb950' else '#f0c060'
    ctx.font = '8px monospace'
    ctx.fillText (if useServo then 'LIVE' else 'SIM'), margin.left, margin.top + 8
    servoColors = [
        '#3fb950'
        '#f3f'
        '#00d4ff'
        '#f0c060'
        '#58a6ff'
        '#ff7b72'
        '#d2a8ff'
        '#ffa657'
    ]
    pairLabels = [
        'F'
        '2'
        '3'
        '4'
    ]
    s = 0
    while s < servoCount
        color = servoColors[s % servoColors.length]
        isLeft = s % 2 == 0
        pairIdx = Math.floor(s / 2)
        ctx.strokeStyle = color
        ctx.lineWidth = if isLeft then 1.2 else 0.9
        ctx.globalAlpha = 0.85
        ctx.setLineDash if isLeft then [] else [
            3
            2
        ]
        ctx.beginPath()
        key = 's' + s
        j = 0
        while j < n
            xx = margin.left + j * xScale
            val = @waveHistory[j][key] or 0
            yy = midY - (val / AMP_REF * ampY)
            if j == 0
                ctx.moveTo xx, yy
            else
                ctx.lineTo xx, yy
            j++
        ctx.stroke()
        ctx.globalAlpha = 1
        ctx.setLineDash []
        lastVal = @waveHistory[n - 1][key] or 0
        labelY = midY - (lastVal / AMP_REF * ampY)
        ctx.fillStyle = color
        ctx.font = '9px monospace'
        ctx.fillText pairLabels[pairIdx] + (if isLeft then 'L' else 'R'), margin.left + pw + 1, labelY + 3
        s++
    return

Model::setFlapState = (params) ->
    `var i`
    i = undefined
    i = undefined
    if !@flapParams
        return
    if params.throttle != undefined
        @flapParams.throttle = params.throttle
    if params.yaw != undefined
        @flapParams.yaw = params.yaw
    if params.frequency != undefined
        @flapParams.frequency = params.frequency
    if params.amplitude != undefined
        @flapParams.amplitude = params.amplitude
    if params.aeroelasticCoef != undefined
        @flapParams.aeroelasticCoef = params.aeroelasticCoef
    if params.glideAeroCoef != undefined
        @flapParams.glideAeroCoef = params.glideAeroCoef
    if params.ferocityDown != undefined
        @flapParams.ferocityDown = params.ferocityDown
    if params.ferocityUp != undefined
        @flapParams.ferocityUp = params.ferocityUp
    if params.ferocityDownL != undefined
        i = 0
        while i < 4
            @flapParams.ferocityDownL[i] = if params.ferocityDownL[i] != undefined then params.ferocityDownL[i] else 4.0
            i++
    if params.ferocityDownR != undefined
        i = 0
        while i < 4
            @flapParams.ferocityDownR[i] = if params.ferocityDownR[i] != undefined then params.ferocityDownR[i] else 4.0
            i++
    if params.ferocityUpL != undefined
        i = 0
        while i < 4
            @flapParams.ferocityUpL[i] = if params.ferocityUpL[i] != undefined then params.ferocityUpL[i] else 4.0
            i++
    if params.ferocityUpR != undefined
        i = 0
        while i < 4
            @flapParams.ferocityUpR[i] = if params.ferocityUpR[i] != undefined then params.ferocityUpR[i] else 4.0
            i++
    if params.phaseShifts != undefined
        i = 0
        while i < 4
            @flapParams.phaseShifts[i] = if params.phaseShifts[i] != undefined then params.phaseShifts[i] else 0
            i++
    if params.mountAngles != undefined
        i = 0
        while i < 4
            @flapParams.mountAngles[i] = if params.mountAngles[i] != undefined then params.mountAngles[i] else 0
            i++
    if params.mountAnglesL != undefined
        i = 0
        while i < 4
            @flapParams.mountAnglesL[i] = if params.mountAnglesL[i] != undefined then params.mountAnglesL[i] else 0
            i++
    if params.mountAnglesR != undefined
        i = 0
        while i < 4
            @flapParams.mountAnglesR[i] = if params.mountAnglesR[i] != undefined then params.mountAnglesR[i] else 0
            i++
    if params.servoCount != undefined and params.servoCount != @flapParams.servoCount
        @flapParams.servoCount = params.servoCount
        @buildOrnithopter Math.max(1, Math.floor(params.servoCount / 2))
    return

Model::rotateTo = (x, y, z) ->
    if @wingPivots
        @modelWrapper.rotation.x = x
        @modelWrapper.rotation.y = y
        @modelWrapper.rotation.z = z
    else if @model
        @model.rotation.x = x
        @modelWrapper.rotation.y = y
        @model.rotation.z = z
    if !@animationFrame
        @render()
    return

Model::rotateBy = (x, y, z) ->
    if !@model and !@wingPivots
        return
    if @wingPivots
        @modelWrapper.rotateX x
        @modelWrapper.rotateY y
        @modelWrapper.rotateZ z
    else
        @model.rotateX x
        @model.rotateY y
        @model.rotateZ z
    if !@animationFrame
        @render()
    return

Model::render = ->
    if !@model and !@wingPivots
        return
    @renderer.render @scene, @camera
    return

Model::resize = ->
    @renderer.setSize @wrapper.width() * 2, @wrapper.height() * 2
    @camera.aspect = @wrapper.width() / @wrapper.height()
    @camera.updateProjectionMatrix()
    @render()
    return

Model::canUseWebGLRenderer = ->
    detector_canvas = undefined
    detector_canvas = document.createElement('canvas')
    window.WebGLRenderingContext and (detector_canvas.getContext('webgl') or detector_canvas.getContext('experimental-webgl'))

Model::dispose = ->
    if @animationFrame
        cancelAnimationFrame @animationFrame
        @animationFrame = null
    if @renderer
        @renderer.forceContextLoss()
        @renderer.dispose()
    return

window.Model = Model